export const emptyMoviesArray = [

];

export const recommendedMovies = [
  {
    id: 1,
    Title: 'Iron Man 3',
    Released: '03 May 2013',
    Runtime: '130 min',
    Actors: 'Robert Downey Jr., Guy Pearce, Gwyneth Paltrow',
    Language: 'English',
    Country: 'United States',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMjE5MzcyNjk1M15BMl5BanBnXkFtZTcwMjQ4MjcxOQ@@._V1_SX300.jpg',
    imdbRating: '7.1',
    BoxOffice: '$409,013,994',
  },
  {
    id: 2,
    Title: 'Avengers: Age of Ultron',
    Released: '01 May 2015',
    Runtime: '141 min',
    Actors: 'Robert Downey Jr., Chris Evans, Mark Ruffalo',
    Language: 'English, Korean',
    Country: 'United States',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMTM4OGJmNWMtOTM4Ni00NTE3LTg3MDItZmQxYjc4N2JhNmUxXkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_SX300.jpg',
    imdbRating: '7.3',
    BoxOffice: '$459,005,868',
  },
  {
    id: 3,
    Title: 'Oppenheimer',
    Released: '21 Jul 2023',
    Runtime: '180 min',
    Actors: 'Cillian Murphy, Emily Blunt, Matt Damon',
    Language: 'English, German, Italian',
    Country: 'United States, United Kingdom',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMDBmYTZjNjUtN2M1MS00MTQ2LTk2ODgtNzc2M2QyZGE5NTVjXkEyXkFqcGdeQXVyNzAwMjU2MTY@._V1_SX300.jpg',
    imdbRating: '8.6',
    BoxOffice: '$302,215,760',
  },
  {
    id: 4,
    Title: 'Avatar: The Way of Water',
    Released: '16 Dec 2022',
    Runtime: '192 min',
    Actors: 'Sam Worthington, Zoe Saldana, Sigourney Weaver',
    Language: 'English',
    Country: 'United States',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BYjhiNjBlODctY2ZiOC00YjVlLWFlNzAtNTVhNzM1YjI1NzMxXkEyXkFqcGdeQXVyMjQxNTE1MDA@._V1_SX300.jpg',
    imdbRating: '7.6',
    BoxOffice: '$684,075,767',
  },
  {
    id: 5,
    Title: 'Spider-Man: No Way Home',
    Released: '17 Dec 2021',
    Runtime: '148 min',
    Actors: 'Tom Holland, Zendaya, Benedict Cumberbatch',
    Language: 'English',
    Country: 'United States',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_SX300.jpg',
    imdbRating: '8.2',
    BoxOffice: '$814,115,070',
  },
  {
    id: 6,
    Title: 'Mad Max: Fury Road',
    Released: '15 May 2015',
    Runtime: '120 min',
    Actors: 'Tom Hardy, Charlize Theron, Nicholas Hoult',
    Language: 'English, Russian',
    Country: 'Australia',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BN2EwM2I5OWMtMGQyMi00Zjg1LWJkNTctZTdjYTA4OGUwZjMyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    imdbRating: '8.1',
    BoxOffice: '$154,280,290',
  },
  {
    id: 7,
    Title: 'Venom',
    Released: '05 Oct 2018',
    Runtime: '112 min',
    Actors: 'Tom Hardy, Michelle Williams, Riz Ahmed',
    Language: 'English, Mandarin, Malay',
    Country: 'United States, China',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNTFkZjdjN2QtOGE5MS00ZTgzLTgxZjAtYzkyZWQ5MjEzYmZjXkEyXkFqcGdeQXVyMTM0NTUzNDIy._V1_SX300.jpg',
    imdbRating: '6.6',
    BoxOffice: '$213,515,506',
  },
  {
    id: 8,
    Title: 'The Matrix',
    Released: '31 Mar 1999',
    Runtime: '136 min',
    Actors: 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss',
    Language: 'English',
    Country: 'United States, Australia',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
    imdbRating: '8.7',
    BoxOffice: '$172,076,928',
  },
  {
    id: 9,
    Title: 'Extraction',
    Released: '24 Apr 2020',
    Runtime: '116 min',
    Actors: 'Chris Hemsworth, Bryon Lerum, Ryder Lerum',
    Language: 'English, Hindi, Bengali',
    Country: 'United States',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMDJiNzUwYzEtNmQ2Yy00NWE4LWEwNzctM2M0MjE0OGUxZTA3XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    imdbRating: '6.8',
    BoxOffice: 'N/A',
  },
  {
    id: 10,
    Title: 'Transformers: Dark of the Moon',
    Released: '29 Jun 2011',
    Runtime: '154 min',
    Actors: 'Shia LaBeouf, Rosie Huntington-Whiteley, Tyrese Gibson',
    Language: 'English, Russian',
    Country: 'United States',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMTkwOTY0MTc1NV5BMl5BanBnXkFtZTcwMDQwNjA2NQ@@._V1_SX300.jpg',
    imdbRating: '6.2',
    BoxOffice: '$352,390,543',
  },
  {
    id: 11,
    Title: 'Deadpool',
    Released: '12 Feb 2016',
    Runtime: '108 min',
    Actors: 'Ryan Reynolds, Morena Baccarin, T.J. Miller',
    Language: 'English',
    Country: 'United States',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BYzE5MjY1ZDgtMTkyNC00MTMyLThhMjAtZGI5OTE1NzFlZGJjXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
    imdbRating: '8.0',
    BoxOffice: '$363,070,709',
  },
  {
    id: 12,
    Title: 'The Expendables 3',
    Released: '15 Aug 2014',
    Runtime: '126 min',
    Actors: 'Sylvester Stallone, Jason Statham, Jet Li',
    Language: 'English, Romanian, Spanish',
    Country: 'France, Germany, Bulgaria, United States',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BODU5ODMyMzg2MV5BMl5BanBnXkFtZTgwMTA2MTcxMjE@._V1_SX300.jpg',
    imdbRating: '6.1',
    BoxOffice: '$39,322,544',
  },
  {
    id: 13,
    Title: 'X-Men: Dark Phoenix LIVE Red Carpet World Premiere',
    Released: '04 Jun 2019',
    Runtime: '71 min',
    Actors: 'Hannah Emily Anderson, Shawn Ashmore, Jessica Chastain',
    Language: 'English',
    Country: 'United States',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMjEzZTI4ODYtMWJjYi00MDQ3LTlkM2EtZGViYmM4ZjU2OTcxXkEyXkFqcGdeQXVyMTE0MjExNA@@._V1_SX300.jpg',
    imdbRating: '6.5',
    BoxOffice: 'N/A',
  },
  {
    id: 14,
    Title: 'Fast X',
    Released: '19 May 2023',
    Runtime: '141 min',
    Actors: 'Vin Diesel, Michelle Rodriguez, Jason Statham',
    Language: 'English',
    Country: 'United States, China',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNzZmOTU1ZTEtYzVhNi00NzQxLWI5ZjAtNWNhNjEwY2E3YmZjXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg',
    imdbRating: '5.8',
    BoxOffice: '$145,960,660',
  },
  {
    id: 15,
    Title: 'Lucy',
    Released: '25 Jul 2014',
    Runtime: '89 min',
    Actors: 'Scarlett Johansson, Morgan Freeman, Choi Min-sik',
    Language: 'English, Mandarin, French, Italian, German, Spanish, Korean',
    Country: 'France, Germany, Taiwan, Canada, United States, United Kingdom',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BODcxMzY3ODY1NF5BMl5BanBnXkFtZTgwNzg1NDY4MTE@._V1_SX300.jpg',
    imdbRating: '6.4',
    BoxOffice: '$126,663,600',
  },
  {
    id: 16,
    Title: 'King Kong',
    Released: '14 Dec 2005',
    Runtime: '187 min',
    Actors: 'Naomi Watts, Jack Black, Adrien Brody',
    Language: 'English',
    Country: 'United States, New Zealand, Germany',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMjYxYmRlZWYtMzAwNC00MDA1LWJjNTItOTBjMzlhNGMzYzk3XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    imdbRating: '7.2',
    BoxOffice: '$218,080,025',
  },
];